### ISSUE TITLE
Console output contains invalid Rancher URL address

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/crane#12]
Crane returns these lines in the output:

```
Alrighty, let's deploy! ᕕ( ᐛ )ᕗ
(But please supervise me at https://url.com//env/123/apps/stacks/456)
Upgrading graphql…
```

But the URL address doesn't work because of the `com//env/` part (Rancher is not happy and you'll get only an empty page).

**Comment by chauffer** [comment]
@mrtnzlml so the issue is the 2 slashes, yeah?

**Comment by mrtnzlml** [comment]
yes
