### ISSUE TITLE
support multiple slack channels

### ISSUE THREAD

**Issue by lucas03** [kiwicom/crane#25]
Since we are pushing all company releases to #releases slack channel, it started to be a bit spammy. That is pretty useful on outages, to find out what was released throughout company within specific time range.
But then developers don't follow releases. I think developers should be aware of all releases related to their projects, that is why I'd like to request option to be able to set `CRANE_SLACK_CHANNEL` as list of channels. So we can use one for general releases and one separate channel for just our releases.

---
🍫This issue has a **bounty of €10**! Check [open.kiwi.com/bounties](https://open.kiwi.com/bounties) for details on how to claim the bounty by solving the issue.

**Comment by underyx** [comment]
Closed with https://github.com/kiwicom/crane/commit/5a56b92674a8aa6713d42e4650fe1e0849099ea0
