### ISSUE TITLE
--no-supervision option

### ISSUE THREAD

**Issue by ksesong** [kiwicom/crane#3]
There are some cases when upgrading takes time (for example, some worker-containers have to complete their tasks before stopping gracefully), such that waiting for the upgrade to complete is time-consuming (and unnecessary, sometimes it might even interfere with the runner timeout). There should be a "--no-supervision" option where `crane` exits without waiting for the upgrade to complete.

**Comment by chauffer** [comment]
Hi @ksesong, apologies for the delay.

`--manual-finish` seems to be the option you're looking for. It will skip the automatic finish upgrade in Rancher.
